### ISSUE TITLE
[FEATURE REQUEST] UI changes

### ISSUE THREAD

**Issue by karbis** [brapstu/Notepad--#2]
Yea just like change it (its meant to be centered in the Y
![UI](https://user-images.githubusercontent.com/102873508/175769520-f4927508-7464-4304-9d94-bdd373a397ab.png)
)

**Comment by brapstu** [comment]
Ok

**Comment by karbis** [comment]
Gg

**Comment by brapstu** [comment]
![image](https://user-images.githubusercontent.com/70806994/175769583-48907e87-bbe4-489e-8dfa-e8ee5851c168.png)

**Comment by karbis** [comment]
thas good
