### ISSUE TITLE
[FEATURE REQUEST] Feature ideas

### ISSUE THREAD

**Issue by karbis** [brapstu/Notepad--#3]
1. Prompt when trying to close app without saving
2. If file open, Display file name at window title
3. Add text size changing (zoom)
4. Text customization
5. Shortcuts to add certain things (time, date, etc)
6. Move all buttons to a topbar

**Comment by brapstu** [comment]
1. added
2. added
3. soon to be in settings tab
4. see 3
5. maybe
6. maybe
